### ISSUE TITLE
Install fails macOS

### ISSUE THREAD

**Issue by timoast** [pkathail/magic#12]
Hi, I've had some issues installing the package on macOS Sierra (10.12.3). Below is the error message after following install instructions:

```
(py3)[~/Documents/GitHub/magic]$ pip3 install .                                                                            *[develop]
Processing /Users/timstuart/Documents/GitHub/magic
    Complete output from command python setup.py egg_info:
    Collecting git+https://github.com/jacoblevine/phenograph.git
      Cloning https://github.com/jacoblevine/phenograph.git to /private/var/folders/9s/hygtzxkd46j8g85t08_9wtlh0000gn/T/pip-79gv61do-build
      Requirement already satisfied (use --upgrade to upgrade): PhenoGraph==1.5.2 from git+https://github.com/jacoblevine/phenograph.git in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages
    Requirement already satisfied: setuptools>=18.0.1 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from PhenoGraph==1.5.2)
    Requirement already satisfied: numpy>=1.9.2 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from PhenoGraph==1.5.2)
    Requirement already satisfied: scipy>=0.16.0 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from PhenoGraph==1.5.2)
    Requirement already satisfied: scikit_learn>=0.17 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from PhenoGraph==1.5.2)
    Requirement already satisfied: psutil>4 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from PhenoGraph==1.5.2)
    Requirement already satisfied: six>=1.6.0 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from setuptools>=18.0.1->PhenoGraph==1.5.2)
    Requirement already satisfied: appdirs>=1.4.0 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from setuptools>=18.0.1->PhenoGraph==1.5.2)
    Requirement already satisfied: packaging>=16.8 in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from setuptools>=18.0.1->PhenoGraph==1.5.2)
    Requirement already satisfied: pyparsing in /Users/timstuart/.virtualenvs/py3/lib/python3.5/site-packages (from packaging>=16.8->setuptools>=18.0.1->PhenoGraph==1.5.2)
    running egg_info
    creating pip-egg-info/magic.egg-info
    writing pip-egg-info/magic.egg-info/PKG-INFO
    writing requirements to pip-egg-info/magic.egg-info/requires.txt
    writing dependency_links to pip-egg-info/magic.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/magic.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/magic.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/magic.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/magic.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9s/hygtzxkd46j8g85t08_9wtlh0000gn/T/pip-upwnp3_8-build/setup.py", line 52, in <module>
        shutil.copytree(setup_dir + '/data/', data_dir)
      File "/Users/timstuart/.virtualenvs/py3/lib/python3.5/shutil.py", line 303, in copytree
        names = os.listdir(src)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/9s/hygtzxkd46j8g85t08_9wtlh0000gn/T/pip-upwnp3_8-build/data/'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9s/hygtzxkd46j8g85t08_9wtlh0000gn/T/pip-upwnp3_8-build/
```

It seems like this is cause by the setup script trying to access a non-existent `/data` directory. I commented out the last few lines in the setup script (https://github.com/pkathail/magic/blob/develop/setup.py#L49 onwards) and the install ran successfully, although there is no test data.

**Comment by dpcook** [comment]
I will add that I have been receiving the same error and have not been able to solve it yet (including fresh Python3/pip3 installs).

**Comment by jonathanronen** [comment]
👍 
The title is misleading; this isn't a mac os issue, it's the issue @timoast mentions, that the setup script tries to access a non-existent `/data` dir, and should be a quick fix for you guys (include the test data, or remove that from the setup script).

**Comment by pkathail** [comment]
I've updated the setup script on the develop branch
