### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by asmagen** [pkathail/magic#23]
Hello,
May I get help solving this?

MacBook-Pro:magic $ magic_gui.py
Traceback (most recent call last):
  File "/usr/local/bin/magic_gui.py", line 5, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

Thanks, A

**Comment by pkathail** [comment]
Do you have Tcl/Tk installed? If not, you can install the correct version depending on what Python version and Mac OS you're using here: https://www.python.org/download/mac/tcltk/#activetcl-8-5-18-0

If you've already done the installation and are still getting this error, it's possible your Python isn't configured to include this module. To fix this, you could try going into the folder where you installed Tcl/Tk and running "make". Alternatively, you could install ActivePython (https://www.activestate.com/activepython), which already includes tkinter, and use that instead of your current Python distribution.

Let me know if the problem persists!
