### ISSUE TITLE
Error when trying different -k and -l parameters

### ISSUE THREAD

**Issue by gufranca** [pkathail/magic#47]
Hi,
I am very excited in using MAGIC in my data but some issues are happening when I try different parameters. I could install the software with no issues, and when I run in the default mode, I get no errors. However, when I try to change the -k:

MAGIC.py csv -d input.csv -o output.csv --cell-axis columns -k 15
###
doing PCA
Computing distances
Traceback (most recent call last):
  File "/usr/local/bin/MAGIC.py", line 112, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/MAGIC.py", line 104, in main
    k=args.k, ka=args.ka, epsilon=args.epsilon, rescale_percent=args.rescale)
  File "/usr/local/lib/python3.5/dist-packages/magic/mg.py", line 1140, in run_magic
    k=k, ka=ka, epsilon=epsilon, rescale=rescale_percent)
  File "/usr/local/lib/python3.5/dist-packages/magic/MAGIC_core.py", line 21, in magic
    distance_metric='euclidean', ka=ka)
  File "/usr/local/lib/python3.5/dist-packages/magic/MAGIC_core.py", line 95, in compute_markov
    nbrs = NearestNeighbors(n_neighbors=k, metric=distance_metric).fit(data)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/neighbors/base.py", line 803, in fit
    return self._fit(X)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/neighbors/base.py", line 229, in _fit
    self.n_neighbors < self._fit_X.shape[0] // 2) and
TypeError: unorderable types: str() < int()
###

This happens even when I specify the -k parameter with the default value (30). I also tried changing -ka (5), as recommended to be ~3 times lower than -k. When I don't specify the -k parameter, it runs nicely. 

Another issue is when I set the -l parameter (log transformation), like -l 1, I get the following error:

MAGIC.py csv -d input.csv -o output.csv --cell-axis columns -l 1
###
Traceback (most recent call last):
  File "/usr/local/bin/MAGIC.py", line 112, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/MAGIC.py", line 101, in main
    scdata.log_transform_scseq_data(pseudocount=args.log_transform)
  File "/usr/local/lib/python3.5/dist-packages/magic/mg.py", line 514, in log_transform_scseq_data
    self.data = np.log(np.add(self.data, pseudocount))
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
###

I really appreciate any advice on how to overcome these issues. 
Thanks a lot.
Gustavo

**Comment by pkathail** [comment]
Hi Gustavo, 

Thanks for pointing this out. It was an issue with casting the command line arguments to the correct type. I've fixed it in the most recent commit, so it should be working now. Please let me know if you're still having problems with it!

**Comment by gufranca** [comment]
Thanks a lot for the kind reply! I will test again! Thanks!
Gustavo
